"""empty message

Revision ID: 69e5916fbdbc
Revises: 1a9b4aedd342
Create Date: 2025-12-22 22:10:44.393894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69e5916fbdbc'
down_revision = '1a9b4aedd342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('kauid'))
        batch_op.drop_column('kauid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kauid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('kauid'), ['kauid'], unique=True)

    # ### end Alembic commands ###
