"""added kauid

Revision ID: 91f2d7bdb155
Revises: 69e5916fbdbc
Create Date: 2026-02-10 16:24:24.360512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f2d7bdb155'
down_revision = '69e5916fbdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kauid', sa.String(length=12), nullable=True))
        batch_op.create_unique_constraint(None, ['kauid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('kauid')

    # ### end Alembic commands ###
